x = [{"BIZDOMAIN":"WTUA:Permits/*/*/*:INFRA_ASSIGN_PROJECT_MANAGER","BIZDOMAIN_VALUE":01,"REC_FUL_NAM":"SAXTHELM","REC_STATUS":"A","VALUE_DESC":"true ^ assignedStaff = null; userExist = false;"},
{"BIZDOMAIN":"WTUA:Permits/*/*/*:INFRA_ASSIGN_PROJECT_MANAGER","BIZDOMAIN_VALUE":02,"REC_FUL_NAM":"SAXTHELM","REC_STATUS":"A","VALUE_DESC":"true ^ assignedArray = getGISBufferInfo(agisService,layerInfraPM,'-1',attrInfraPMUser,attrInfraPMName);"},
{"BIZDOMAIN":"WTUA:Permits/*/*/*:INFRA_ASSIGN_PROJECT_MANAGER","BIZDOMAIN_VALUE":03,"REC_FUL_NAM":"SAXTHELM","REC_STATUS":"A","VALUE_DESC":"!matches(assignedArray[0]['INDYAD'],undefined,null) ^ if(aa.person.getUser(assignedArray[0]['INDYAD']).getSuccess()) userExist = true;"},
{"BIZDOMAIN":"WTUA:Permits/*/*/*:INFRA_ASSIGN_PROJECT_MANAGER","BIZDOMAIN_VALUE":04,"REC_FUL_NAM":"SAXTHELM","REC_STATUS":"A","VALUE_DESC":"userExist ^ assignCap(assignedArray[0]['INDYAD']); showMessage = true; message = ''; comment('The assigned project manager is: <BR> userid = ' + assignedArray[0]['INDYAD'] + '<BR> name = ' + assignedArray[0]['NAME']);"},
{"BIZDOMAIN":"WTUA:Permits/*/*/*:INFRA_ASSIGN_PROJECT_MANAGER","BIZDOMAIN_VALUE":05,"REC_FUL_NAM":"SAXTHELM","REC_STATUS":"A","VALUE_DESC":"!userExist ^ showMessage = true; message = ''; comment('The assigned project manager could not be found in GIS, must manually assign project manager, follow up with GIS Administrator to ensure GIS layer is accurate');"},
{"BIZDOMAIN":"WTUA:Permits/Improvement Location Permit/*/*:CALC_ILP_NEW_ACCY_FEE","BIZDOMAIN_VALUE":01,"REC_FUL_NAM":"KHOBDAY","REC_STATUS":"A","VALUE_DESC":"true ^ totSF = 0"},
{"BIZDOMAIN":"WTUA:Permits/Improvement Location Permit/*/*:CALC_ILP_NEW_ACCY_FEE","BIZDOMAIN_VALUE":02,"REC_FUL_NAM":"KHOBDAY","REC_STATUS":"A","VALUE_DESC":"typeof(DEVELOPMENTSTANDARDS) == 'object' ^ for ( x in DEVELOPMENTSTANDARDS) if (DEVELOPMENTSTANDARDS [x] ['Development Standard'] == 'Main Flr') totSF+=parseInt(DEVELOPMENTSTANDARDS[x]['Proposed'])"},
{"BIZDOMAIN":"WTUA:Permits/Improvement Location Permit/*/*:CALC_ILP_NEW_ACCY_FEE","BIZDOMAIN_VALUE":03,"REC_FUL_NAM":"KHOBDAY","REC_STATUS":"A","VALUE_DESC":"^ addFee('COM_INDUST','ILP','FINAL',totSF,'N')"},
{"BIZDOMAIN":"WTUA:Permits/Sewer Connection/*/*:ASSESS_FEES_LOOP","BIZDOMAIN_VALUE":01,"REC_FUL_NAM":"MYOUNG","REC_STATUS":"A","VALUE_DESC":"true ^ assessedFee = 0;"},
{"BIZDOMAIN":"WTUA:Permits/Sewer Connection/*/*:ASSESS_FEES_LOOP","BIZDOMAIN_VALUE":02,"REC_FUL_NAM":"MYOUNG","REC_STATUS":"A","VALUE_DESC":"FEETABLE[x]['Rate Type'] == '15 YEAR LAW' ^ assessedFee = FEETABLE[x]['Assessment Area'] * FEETABLE[x]['Assessment Rate']; updateFee('SWR_15YRLAW','INFRA_SWR','FINAL',assessedFee,invoiceFees);"},
{"BIZDOMAIN":"WTUA:Permits/Sewer Connection/*/*:ASSESS_FEES_LOOP","BIZDOMAIN_VALUE":03,"REC_FUL_NAM":"MYOUNG","REC_STATUS":"A","VALUE_DESC":"FEETABLE[x]['Rate Type'] == 'PRO-RATA' ^ assessedFee = FEETABLE[x]['Assessment Area'] * 2202.29; updateFee('SWR_PRORATA','INFRA_SWR','FINAL',FEETABLE[x]['Assessment Area'],invoiceFees)"},
{"BIZDOMAIN":"WTUA:Permits/Sewer Connection/*/*:ASSESS_FEES_LOOP","BIZDOMAIN_VALUE":04,"REC_FUL_NAM":"MYOUNG","REC_STATUS":"A","VALUE_DESC":"FEETABLE[x]['Rate Type'] == 'ADMINISTRATIVE' ^ assessedFee = FEETABLE[x]['Assessment Area'] * 367; updateFee('SWR_SSAADMIN','INFRA_SWR','FINAL',FEETABLE[x]['Assessment Area'],invoiceFees)"},
{"BIZDOMAIN":"WTUA:Permits/Sewer Connection/*/*:ASSESS_FEES_LOOP","BIZDOMAIN_VALUE":05,"REC_FUL_NAM":"MYOUNG","REC_STATUS":"A","VALUE_DESC":"true ^ totalFA += assessedFee; FEETABLE[x]['Fee Total'] = '$' + assessedFee.toFixed(2);"},
{"BIZDOMAIN":"WTUB:Permits/*/*/*:PLAT_BOND_CHECKS","BIZDOMAIN_VALUE":01,"REC_FUL_NAM":"SAXTHELM","REC_STATUS":"A","VALUE_DESC":"!matches(platCase,null,'') && aa.cap.getCapID(platCase).getSuccess() ^ prelimPlatComplete = false; showMessage = true;"},
{"BIZDOMAIN":"WTUB:Permits/*/*/*:PLAT_BOND_CHECKS","BIZDOMAIN_VALUE":02,"REC_FUL_NAM":"SAXTHELM","REC_STATUS":"A","VALUE_DESC":"^ platCapId = getApplication(platCase); holdId = capId; capId = platCapId; prelimPlatComplete = isTaskComplete('Preliminary Plat Closure'); capId = holdId;"},
{"BIZDOMAIN":"WTUB:Permits/*/*/*:PLAT_BOND_CHECKS","BIZDOMAIN_VALUE":03,"REC_FUL_NAM":"SAXTHELM","REC_STATUS":"A","VALUE_DESC":"^ if(!prelimPlatComplete) comment('Preliminary Plat Closure is not complete on Plat Case #: ' + platCapId.getCustomID() + ' cannot continue until complete.' + '<BR><BR>This will eventually stop the process, but for now during testing I will just show a message.');"},
{"BIZDOMAIN":"WTUB:Permits/*/*/*:PLAT_BOND_CHECKS","BIZDOMAIN_VALUE":04,"REC_FUL_NAM":"SAXTHELM","REC_STATUS":"A","VALUE_DESC":"!matches(platCase,null,'') && !aa.cap.getCapID(platCase).getSuccess() ^ showMessage = true; comment('Case is not currently linked to a plat, must be linked to a plat prior to proceeding.'  + '<BR><BR>This will eventually stop the process, but for now during testing I will just show a message.');"},
{"BIZDOMAIN":"WTUB:Permits/*/*/*:PLAT_BOND_CHECKS","BIZDOMAIN_VALUE":05,"REC_FUL_NAM":"SAXTHELM","REC_STATUS":"A","VALUE_DESC":"((isTaskActive('Bonding') && !isTaskStatus('Bonding','Other Perf. Security Received')) && PERFBONDEDIMPROVEMENTS[0]['Improvement Type'] == undefined) ^ showMessage = true; comment('There are currently no performance bonds listed, must have at least one bond to proceed.'); cancel = true;"}]
for (var i in x) {
	row = x[i];
	aa.bizDomain.createBizDomain(row.BIZDOMAIN, row.BIZDOMAIN_VALUE, row.REC_STATUS, row.VALUE_DESC)
	}
	