{Fee Schedule} == "a sidewalk cafe" ^ feeQty = 1; feeSch = "BOPFLATFEES";feeCode = "C04";branch("BoPFeeCalc01")
{Fee Schedule} == "b other SAP, no expansion" ^ feeQty = 1; feeSch = "BOPFLATFEES";feeCode = "C04";branch("BoPFeeCalc01")
{Fee Schedule} == "c expansion up to 49,999 sf" ^ feeQty = 1; feeSch = "BOPFLATFEES";feeCode = "C06";branch("BoPFeeCalc01")
{Fee Schedule} == "d expansion between 50,000 and 249,999 sf" ^ feeQty = 1; feeSch = "BOPFLATFEES";feeCode = "C09";branch("BoPFeeCalc01")
{Fee Schedule} == "e expansion greater than 250,000 sf" ^ feeQty = 1; feeSch = "BOPFLATFEES";feeCode = "C11";branch("BoPFeeCalc01")
{Fee Schedule} == "f cell tower" ^ feeQty = 1; feeSch = "BOPFLATFEES";feeCode = "C04";branch("BoPFeeCalc01")