true ^ showDebug = false; showMessage = false;
inspType == "Initial Inspection" && inspResult == "No Violation Found" ^ closeTask("Initial Inspection","No Violation Found");activateTask("Close");closeTask("Close","Closed");
inspType == "Initial Inspection" && inspResult == "Citation Served" ^ closeTask("Initial Inspection","Citation Served"); deactivateTask("Generate Notice-Citation"); activateTask("Pre-Court Inspection"); assignTask("Pre-Court Inspection",currentUserID);
inspType == "Initial Inspection" && inspResult == "Citation to Clerical" ^ closeTask("Initial Inspection","Citation to Clerical");activateTask("Generate Notice-Citation");
inspType == "Initial Inspection" && inspResult == "Notice to Clerical" ^ closeTask("Initial Inspection","Notice to Clerical");activateTask("Generate Notice-Citation");
inspType == "Initial Inspection" && inspResult == "Stop Work Posted" ^ closeTask("Initial Inspection","Stop Work Posted");activateTask("Follow Up Inspection");
inspType == "Initial Inspection" && inspResult == "Notice HD-Stop Work Posted" ^ closeTask("Initial Inspection","Final-UTGE");activateTask("Follow Up Inspection");
inspType == "Initial Inspection" && inspResult == "Final-UTGE" ^ closeTask("Initial Inspection","Final-UTGE");activateTask("Supervisor Review");
inspType == "Generate Notice-Citation" && inspResult == "Received Citation Certified Receipt" ^ closeTask("Generate Notice-Citation","Received Citation Certified Receipt");activateTask("Pre-Court Inspection");
inspType == "Generate Notice-Citation" && inspResult == "Citation Served by Sheriff" ^ closeTask("Generate Notice-Citation","Citation Served by Sheriff");activateTask("Pre-Court Inspection");
inspType == "Generate Notice-Citation" && inspResult == "Citation Unserved" ^ closeTask("Generate Notice-Citation","Citation Unserved");activateTask("Supervisor Review");
inspType == "Generate Notice-Citation" && inspResult == "Return to Supervisor" ^ closeTask("Generate Notice-Citation","Return to Supervisor");activateTask("Supervisor Review");
inspType == "Generate Notice-Citation" && inspResult == "Notice Mailed-Returned Undeliverable" ^ closeTask("Generate Notice-Citation","Notice Mailed-Returned Undeliverable");activateTask("Supervisor Review");
inspType == "Generate Notice-Citation" && inspResult == "Received Certified Notice Receipt" ^ closeTask("Generate Notice-Citation","Received Certified Notice Receipt");activateTask("Pre-Court Inspection");
inspType == "Follow Up Inspection" && inspResult == "Citation Served" ^ closeTask("Follow Up Inspection","Citation Served");activateTask("Pre-Court Inspection");
inspType == "Follow Up Inspection" && inspResult == "Citation to Clerical" ^ closeTask("Follow Up Inspection","Citation to Clerical");activateTask("Generate Notice-Citation");
inspType == "Follow Up Inspection" && inspResult == "Complied" ^ closeTask("Follow Up Inspection","Complied");activateTask("Close");closeTask("Close","Closed");
inspType == "Follow Up Inspection" && inspResult == "No Violation Found" ^ closeTask("Follow Up Inspection","No Violation Found");activateTask("Close");closeTask("Close","Closed");
inspType == "Pre-Court Inspection" && inspResult == "In Compliance" ^ closeTask("Pre-Court Inspection","In Compliance");activateTask("Court");
inspType == "Pre-Court Inspection" && inspResult == "Not in Compliance" ^ closeTask("Pre-Court Inspection","Not in Compliance");activateTask("Court");