true ^ showDebug = false; showMessage = false;
true ^ feeRow = ELECTRICALSERVICES[eachrow];
feeRow["Service Amps"] == "1-200" ^ updateFee("S01","BLDELECTRICAL","FINAL", parseInt(feeRow["Service Quantity"]),"Y");
feeRow["Service Amps"] == "201-800" ^ updateFee("S02","BLDELECTRICAL","FINAL", parseInt(feeRow["Service Quantity"]),"Y");
feeRow["Service Amps"] == "801-1200" ^ updateFee("S03","BLDELECTRICAL","FINAL", parseInt(feeRow["Service Quantity"]),"Y");
feeRow["Service Amps"] == "1201-2000" ^ updateFee("S04","BLDELECTRICAL","FINAL", parseInt(feeRow["Service Quantity"]),"Y");
feeRow["Service Amps"] == "2001-4000" ^ updateFee("S05","BLDELECTRICAL","FINAL", parseInt(feeRow["Service Quantity"]),"Y");
feeRow["Service Amps"] == "Over 4000" ^ updateFee("S06","BLDELECTRICAL","FINAL", parseInt(feeRow["Service Quantity"]),"Y");
feeRow["Feeder Amps"] == "1-30" ^ updateFee("F01","BLDELECTRICAL","FINAL", parseInt(feeRow["Feeder Quantity"]),"Y");
feeRow["Feeder Amps"] == "31-100" ^ updateFee("F02","BLDELECTRICAL","FINAL", parseInt(feeRow["Feeder Quantity"]),"Y");
feeRow["Feeder Amps"] == "101-200" ^ updateFee("F03","BLDELECTRICAL","FINAL", parseInt(feeRow["Feeder Quantity"]),"Y");
feeRow["Feeder Amps"] == "201-800" ^ updateFee("F04","BLDELECTRICAL","FINAL", parseInt(feeRow["Feeder Quantity"]),"Y");
feeRow["Feeder Amps"] == "801-1200" ^ updateFee("F05","BLDELECTRICAL","FINAL", parseInt(feeRow["Feeder Quantity"]),"Y");
feeRow["Feeder Amps"] == "1201-2000" ^ updateFee("F06","BLDELECTRICAL","FINAL", parseInt(feeRow["Feeder Quantity"]),"Y");
feeRow["Feeder Amps"] == "2001-4000" ^ updateFee("F07","BLDELECTRICAL","FINAL", parseInt(feeRow["Feeder Quantity"]),"Y");
feeRow["Feeder Amps"] == "Over 4000" ^ updateFee("F08","BLDELECTRICAL","FINAL", parseInt(feeRow["Feeder Quantity"]),"Y");
feeRow["Branch Circuit Amps"] == "1-30" ^ updateFee("C01","BLDELECTRICAL","FINAL", parseInt(feeRow["Branch Circuit Quantity"]),"Y");
feeRow["Branch Circuit Amps"] == "31-100" ^ updateFee("C02","BLDELECTRICAL","FINAL", parseInt(feeRow["Branch Circuit Quantity"]),"Y");
feeRow["Branch Circuit Amps"] == "101-200" ^ updateFee("C03","BLDELECTRICAL","FINAL", parseInt(feeRow["Branch Circuit Quantity"]),"Y");
feeRow["Branch Circuit Amps"] == "201-800" ^ updateFee("C04","BLDELECTRICAL","FINAL", parseInt(feeRow["Branch Circuit Quantity"]),"Y");
feeRow["Branch Circuit Amps"] == "801-1200" ^ updateFee("C05","BLDELECTRICAL","FINAL", parseInt(feeRow["Branch Circuit Quantity"]),"Y");
feeRow["Branch Circuit Amps"] == "1201-2000" ^ updateFee("C06","BLDELECTRICAL","FINAL", parseInt(feeRow["Branch Circuit Quantity"]),"Y");
feeRow["Branch Circuit Amps"] == "2001-4000" ^ updateFee("C07","BLDELECTRICAL","FINAL", parseInt(feeRow["Branch Circuit Quantity"]),"Y");
feeRow["Branch Circuit Amps"] == "Over 4000" ^ updateFee("C08","BLDELECTRICAL","FINAL", parseInt(feeRow["Branch Circuit Quantity"]),"Y");
{Type of Permit} == "Temporary Pole" && {Number of Temporary Poles} != null ^ updateFee("A01","BLDELECTRICAL","FINAL",{Number of Temporary Poles},"Y");
{Low Voltage} == "CHECKED" && {Total Square Footage} != null ^ updateFee("A03","BLDELECTRICAL","FINAL",{Total Square Footage},"Y");
{Type of Permit} == "Disconnect/Reconnect" && {Disconnect/Reconnect Quantity} != null ^ updateFee("A02","BLDELECTRICAL","FINAL",{Disconnect/Reconnect Quantity},"Y");