true ^ showDebug = false; showMessage = false;
{Site Inspection Residential} == "Yes" ^ updateFee("SD04","SITEDEV", "FINAL", 1, "N");
{Site Inspection Multi Family} == "Yes" ^ updateFee("SD05","SITEDEV", "FINAL", 1, "N");
{Site Inspection Commercial} == "Yes" ^ updateFee("SD06","SITEDEV", "FINAL", 1, "N");
{Pipe Inspection Storm 12+ Inches} != null ^ updateFee("SD07","SITEDEV", "FINAL", {Pipe Inspection Storm 12+ Inches} , "N");
{Pipe Inspection Sanitary 8+ Inches} != null ^ updateFee("SD08","SITEDEV", "FINAL", {Pipe Inspection Sanitary 8+ Inches} , "N");
{Pipe Inspection Storm & Sanitary Structures} != null ^ updateFee("SD09","SITEDEV", "FINAL", {Pipe Inspection Storm & Sanitary Structures} , "N");
{Sewer Connection Inspection Residential} == 'Yes' ^ updateFee("SD10","SITEDEV", "FINAL", 1, "N");
{Sewer Connection Inspection Multi Family} != null ^ updateFee("SD11","SITEDEV", "FINAL", {Sewer Connection Inspection Multi Family} , "N");
{Sewer Connection Inspection Commercial} != null ^ updateFee("SD12","SITEDEV", "FINAL", {Sewer Connection Inspection Commercial} , "N");
{Driveway Inspection} != null ^ updateFee("SD13","SITEDEV", "FINAL", {Driveway Inspection} , "N");
{Sidewalk Inspection} != null ^ updateFee("SD14","SITEDEV", "FINAL", {Sidewalk Inspection} , "N");
{Curb & Gutter Inspection} != null ^ updateFee("SD15","SITEDEV", "FINAL", {Curb & Gutter Inspection} , "N");
{Subdivision Plan Review} != null ^ updateFee("SD16","SITEDEV", "FINAL", {Subdivision Plan Review} , "N");
{Subdivision Curb & Gutter} != null ^ updateFee("SD17","SITEDEV", "FINAL", {Subdivision Curb & Gutter} , "N");
{Subdivision Street Paving} != null ^ updateFee("SD18","SITEDEV", "FINAL", {Subdivision Street Paving} , "N");
{Subdivision Land Disturbance} != null ^ updateFee("SD19","SITEDEV", "FINAL", {Subdivision Land Disturbance} , "N");
{Sewer Capacity Cert Residential} == "Yes" ^ updateFee("SD20","SITEDEV", "FINAL", 1, "N");
{Sewer Capacity Cert Commercial <2500 gpd} == "CHECKED" ^ updateFee("SD21","SITEDEV", "FINAL", 1 , "N");
{Sewer Capacity Cert Commercial >2500 gpd} == "CHECKED" ^ updateFee("SD22","SITEDEV", "FINAL", 1 , "N");
{Capacity Analysis} == "CHECKED" ^ updateFee("SD23","SITEDEV", "FINAL", 1, "N");
{Modeling & Alternative Analysis} != null ^ updateFee("SD24","SITEDEV", "FINAL", {Modeling & Alternative Analysis} , "N");
{NPDES} == "Yes" && {Disturbed Acreage} == null ^ message="NPDES fee cannot be calculated because the Disturbed Acreage has not been entered"; showMessage = true ;
{NPDES} == "Yes" && {Disturbed Acreage} != null ^ updateFee("SD25","SITEDEV", "FINAL", {Disturbed Acreage} , "N");
{Working without Permit} > 1000 ^ editAppSpecific("Working without Permit", 1000); message="Maximum penalty fee is $1000, the fee amount has been changed"; showMessage = true ;
{Working without Permit} != null ^ updateFee("SD26","SITEDEV", "FINAL", {Working without Permit} , "N");