true ^ showDebug = true; showMessage = true;
true ^ branch ("CMN:Building/*/*/*:Unpaid Balance");
true ^ branch ("CMN:Building/*/*/*:Permit Issuance");
wfTask == "Site Development Review" && ((wfStatus == "Approved") || (wfStatus == "Approved with Conditions") || (wfStatus == "Admin Review")) ^ branch ("CMN:Building/*/*/*:Check Stormwater");
wfTask == "Zoning Review" && proximity("Atlanta_AA","Elementary Schools",10000) ^ showMessage=true; message="Warning! That parcel may be within 10000 feet"
wfTask == "Certificate of Occupancy" && wfStatus == "Issued" ^ showMessage = true; feesOwed = true; finalComplete = true; childA = getChildren("Building/*/*/*",capId); if(childA != null) for (x in childA) branch ("CMN:Building/*/*/*:Related CAPS Inspection and Balances");
wfTask == "Grease Trap Review" && ((wfStatus == "Approved") || (wfStatus == "Approved with Conditions") || (wfStatus == "Admin Review")) && typeof(GREASETRAP) == "undefined" ^  message="Workflow Task Can't Be Updated Because There Are No Grease Traps Documented In The ASI Table"; showMessage = true ; cancel = true;
wfTask == "Certificate of Occupancy" && wfStatus == "Issued" && {Sewer Tap Form Required} == "CHECKED" && {Sewer Tap Form Received} != "CHECKED" ^ showMessage = true; message = "SITE DEVELOPMENT: Sewer Tap Form required before C/O can be issued.  Contact someone in Site Development."; cancel = true;
wfTask == "Certificate of Occupancy" && wfStatus == "Issued" && appHasCondition(null, "Applied", "Development Authority Financing", null) ^ showMessage = true; message = "HOUSING: This development is receiving financial assistance from a Development Authority.  Prior to the issuance of a Certificate of Occupancy, the applicant must complete a LURA provided by the Office of Housing and Community Development.  Once completed, this LURA must be submitted to the Office of Housing and Community Development."; cancel = true;
wfTask == "Certificate of Occupancy" && wfStatus == "Issued" && parcelConditionExists("Planning Condition") ^ showMessage = true; message = "PLANNING: Condition on Planning SAP record.  The City of Atlanta Zoning Ordinance mandates that a developer or agent submits to the Director of Office of Zoning and Development evidence of compliance with the requirements of the Transportation Management Plan, as applicable. For specific details and to release this hold, contact Office of Zoning and Development staff member from the SAP section, at (404) 330-6145."; cancel = true;
(appMatch("Building/Residential/New/NA") || appMatch("Building/Residential/Addition/NA") || appMatch("Building/Residential/Alteration/NA") || appMatch("Building/Residential/Conversion/NA") || appMatch("Building/Residential/Miscellaneous/*") || appMatch("Building/Residential/Pool/NA")) && wfTask == "Site Development Review" && wfStatus == "Approved" && typeof(GREENINFRASTRUCTURE )!= "object" ^ showMessage = true;message = "Please complete Green Infrastructure ASI table before updating workflow task status";cancel = true;
(appMatch("Building/Residential/New/NA") || appMatch("Building/Residential/Addition/NA") || appMatch("Building/Residential/Alteration/NA") || appMatch("Building/Residential/Conversion/NA") || appMatch("Building/Residential/Miscellaneous/*") || appMatch("Building/Residential/Pool/NA")) && wfTask == "Site Development Review" && wfStatus == "Approved with Conditions" && typeof(GREENINFRASTRUCTURE )!= "object" ^ showMessage = true;message = "Please complete Green Infrastructure ASI table before updating workflow task status";cancel = true;
(appMatch("Building/Residential/New/NA") || appMatch("Building/Residential/Addition/NA") || appMatch("Building/Residential/Alteration/NA") || appMatch("Building/Residential/Conversion/NA") || appMatch("Building/Residential/Miscellaneous/*") || appMatch("Building/Residential/Pool/NA")) && wfTask == "Site Development Review" && wfStatus == "Admin Review" && typeof(GREENINFRASTRUCTURE )!= "object" ^ showMessage = true;message = "Please complete Green Infrastructure ASI table before updating workflow task status";cancel = true;
(appMatch("Building/Commercial/Addition/NA") || appMatch("Building/Commercial/Alteration/NA") || appMatch("Building/Commercial/Conversion/NA") || appMatch("Building/Commercial/Miscellaneous/*") || appMatch("Building/Commercial/Demolition/NA") || appMatch("Building/Commercial/Land Development/NA") || appMatch("Building/Commercial/Pool/NA") || appMatch("Building/Multi Family/Land Development/NA") || appMatch("Building/Multi Family/Addition/NA") || appMatch("Building/Multi Family/Alteration/NA") || appMatch("Building/Multi Family/Conversion/NA") || appMatch("Building/Multi Family/Demolition/NA")) && wfTask == "Site Development Review" && wfStatus == "Approved" && typeof(RATEREDUCTIONWATERQUALITY)!= "object" && matches(wfStatus,"Approved","Approved with Conditions","Admin Review") ^ showMessage = true;message = "Please complete Green Infrastructure and Rate Reduction/Water Quality ASI table before updating workflow task status";cancel = true;
(appMatch("Building/Commercial/Addition/NA") || appMatch("Building/Commercial/Alteration/NA") || appMatch("Building/Commercial/Conversion/NA") || appMatch("Building/Commercial/Miscellaneous/*") || appMatch("Building/Commercial/Demolition/NA") || appMatch("Building/Commercial/Land Development/NA") || appMatch("Building/Commercial/Pool/NA") || appMatch("Building/Multi Family/Land Development/NA") || appMatch("Building/Multi Family/Addition/NA") || appMatch("Building/Multi Family/Alteration/NA") || appMatch("Building/Multi Family/Conversion/NA") || appMatch("Building/Multi Family/Demolition/NA")) && wfTask == "Site Development Review" && wfStatus == "Approved with Conditions" && typeof(RATEREDUCTIONWATERQUALITY)!= "object" && matches(wfStatus,"Approved","Approved with Conditions","Admin Review") ^ showMessage = true;message = "Please complete Green Infrastructure and Rate Reduction/Water Quality ASI table before updating workflow task status";cancel = true;
(appMatch("Building/Commercial/Addition/NA") || appMatch("Building/Commercial/Alteration/NA") || appMatch("Building/Commercial/Conversion/NA") || appMatch("Building/Commercial/Miscellaneous/*") || appMatch("Building/Commercial/Demolition/NA") || appMatch("Building/Commercial/Land Development/NA") || appMatch("Building/Commercial/Pool/NA") || appMatch("Building/Multi Family/Land Development/NA") || appMatch("Building/Multi Family/Addition/NA") || appMatch("Building/Multi Family/Alteration/NA") || appMatch("Building/Multi Family/Conversion/NA") || appMatch("Building/Multi Family/Demolition/NA")) && wfTask == "Site Development Review" && wfStatus == "Admin Review" && typeof(RATEREDUCTIONWATERQUALITY)!= "object" && matches(wfStatus,"Approved","Approved with Conditions","Admin Review") ^ showMessage = true;message = "Please complete Green Infrastructure and Rate Reduction/Water Quality ASI table before updating workflow task status";cancel = true;