SELECT
    A.L1_HSE_NBR_START,
    A.L1_STR_NAME,
    A.L1_STR_SUFFIX,
    A.L1_STR_SUFFIX_DIR,
    A.L1_UNIT_TYPE,
    A.L1_UNIT_START,
    A.L1_ADDR_STATUS,
    A.L1_PRIMARY_ADDR_FLG,
    A.REC_STATUS,
    P.L1_PARCEL_NBR,
    P.L1_PRIMARY_PAR_FLG,
    P.L1_PARCEL_STATUS,
    ENT.OBJECT_ID,
    AGIS.GIS_ID

FROM L3PARCEL P
LEFT OUTER JOIN XPARADDR XPA ON
P.L1_PARCEL_NBR = XPA.L1_PARCEL_NBR
AND P.SOURCE_SEQ_NBR = XPA.SOURCE_SEQ_NBR

LEFT OUTER JOIN L3ADDRES A ON
XPA.L1_ADDRESS_NBR = A.L1_ADDRESS_NBR
AND XPA.SOURCE_SEQ_NBR = A.SOURCE_SEQ_NBR

LEFT OUTER JOIN XPAROWNR XPO ON
P.L1_PARCEL_NBR = XPO.L1_PARCEL_NBR
AND P.SOURCE_SEQ_NBR = XPO.SOURCE_SEQ_NBR

LEFT OUTER JOIN L3OWNERS O ON
XPO.L1_OWNER_NBR = O.L1_OWNER_NBR
AND XPO.SOURCE_SEQ_NBR = O.SOURCE_SEQ_NBR

LEFT OUTER JOIN AGIS_OBJECT_ENT ENT ON
P.L1_PARCEL_NBR = ENT.ENT_ID
LEFT OUTER JOIN AGIS_OBJECT AGIS ON
ENT.OBJECT_ID = AGIS.OBJECT_ID

ORDER BY 
A.L1_STR_NAME,
A.L1_STR_SUFFIX,
A.L1_STR_SUFFIX_DIR,
A.L1_HSE_NBR_START