true ^ showDebug = true; showMessage = true;
true ^ feeRow = SIGNINFORMATION[eachrow];
feeRow["Sign Type"] == "Building Signature" ^ addFee("SPLAN02","SIGN","FINAL",parseInt(feeRow["SqFt"]),"Y");
feeRow["Sign Type"] == "Business Identification" ^ addFee("SPLAN02","SIGN","FINAL",parseInt(feeRow["SqFt"]),"Y");
feeRow["Sign Type"] == "Canopy" ^ addFee("SPLAN02","SIGN","FINAL",parseInt(feeRow["SqFt"]),"Y");
feeRow["Sign Type"] == "Institutional" ^ addFee("SPLAN02","SIGN","FINAL",parseInt(feeRow["SqFt"]),"Y");
feeRow["Sign Type"] == "Large Screen Video Display" ^ addFee("SPLAN02","SIGN","FINAL",parseInt(feeRow["SqFt"]),"Y");
feeRow["Sign Type"] == "Marquee" ^ addFee("SPLAN02","SIGN","FINAL",parseInt(feeRow["SqFt"]),"Y");
feeRow["Sign Type"] == "Neighborhood Identification" ^ addFee("SPLAN02","SIGN","FINAL",parseInt(feeRow["SqFt"]),"Y");
feeRow["Sign Type"] == "Portable" ^ addFee("SPLAN02","SIGN","FINAL",parseInt(feeRow["SqFt"]),"Y");
feeRow["Sign Type"] == "Shopping Center" ^ addFee("SPLAN02","SIGN","FINAL",parseInt(feeRow["SqFt"]),"Y");
feeRow["Sign Type"] == "General Advertising" ^ addFee("SPLAN02","SIGN","FINAL",parseInt(feeRow["SqFt"]),"Y");
cap.isCreatedByACA() ^ branch("CMN:Building/*/*/*:Calc ACA Convenience Fee");