true ^ showDebug = false; showMessage = false;
true ^ feeRow = VENTILATION[eachrow];
feeRow["VENTILATION"] == "Residential Bath Fans and Dryer Vents" ^ addFee("D01","BLDHVAC","FINAL",parseInt(feeRow["Quantity"]),"Y");
feeRow["VENTILATION"] == "Commercial Parts" ^ addFee("D02","BLDHVAC","FINAL",parseInt(feeRow["Quantity"]),"Y");
feeRow["VENTILATION"] == "Commercial Bath Fans and Dryer Vents" ^ addFee("D03","BLDHVAC","FINAL",parseInt(feeRow["Quantity"]),"Y");
feeRow["VENTILATION"] == "Grease Hoods" ^ addFee("D04","BLDHVAC","FINAL",parseInt(feeRow["Quantity"]),"Y");
feeRow["VENTILATION"] == "Duct Alterations" ^ addFee("E01","BLDHVAC","FINAL",parseInt(feeRow["Quantity"]),"Y");
feeRow["VENTILATION"] == "Public Safety Inspections" ^ addFee("F01","BLDHVAC","FINAL",parseInt(feeRow["Quantity"]),"Y");
feeRow["VENTILATION"] == "Change of Contractor" ^ addFee("F02","BLDHVAC","FINAL",parseInt(feeRow["Quantity"]),"Y");
feeRow["VENTILATION"] == "Multi-Family Per Apt or Condo" ^ addFee("MULTI","BLDHVAC","FINAL",parseInt(feeRow["Quantity"]),"Y");
feeRow["VENTILATION"] == "Other" ^ addFee("MISC","BLDHVAC","FINAL",parseInt(feeRow["Quantity"]),"Y");