true ^ showDebug = false; showMessage = true;
true ^ branch ("CMN:Building/*/*/*:Calc Valuation");
{Adjusted Calculated Value} > estValue ^ permitAmt = ({Adjusted Calculated Value} * .007); editAppSpecific("Total Cost of Construction",{Adjusted Calculated Value});
estValue > {Adjusted Calculated Value} ^ permitAmt = (estValue * .007); editAppSpecific("Total Cost of Construction",estValue);
permitAmt != null ^ updateFee("BPERMIT01", "BUILDING", "FINAL", permitAmt, "N", "Y");
true ^ planDeposit01 = feeAmount("BPLAN01");
true ^ planDeposit02 = feeAmount("BPLAN02");
true ^ planDeposit03 = feeAmount("BPLAN03");
true ^ planDeposit = (planDeposit01 + planDeposit02 + planDeposit03);
true ^ permitFee = feeAmount("BPERMIT01", "NEW");
true ^ permitInv = feeAmount("BPERMIT01","INVOICED");
true ^ permitTot = (permitFee - permitInv);
planDeposit != null || planDeposit > 0 ^ permitNet = (permitTot - planDeposit);
planDeposit == null || planDeposit == 0 ^ permitNet = permitTot;
permitNet < 0 ^ permitNet = 0;
planDeposit == null || planDeposit == 0 && permitNet < 150 ^ permitNet = 150;
true ^ updateFee("BPERMIT01", "BUILDING", "FINAL", permitNet, "N", "Y");
cap.isCreatedByACA() ^ branch("CMN:Building/*/*/*:Calc ACA Convenience Fee");
